# Site settings
title: Tên Blog
description: "Write an awesome description for your new site here."
theme: minima

# URL settings
baseurl: ""
url: "https://conghcbapjp.github.io"

# Social links
github_username: conghcbapjp
twitter_username: conghcbapjp

# Author settings
author:
  name: Your Name
  bio: "Mô tả ngắn về bản thân"
  location: "Đà Nẵng - Việt Nam"
  email: your-email@domain.com

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-github-metadata
